<a href="https://colab.research.google.com/github/hyh-sherry/concord_chatbot/blob/master/mock_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# install library faker as customer name generator
pip install faker

In [3]:
# import necessary libraries
import random
import pandas as pd
from faker import Faker

### Customer data: name, gender, age, destination category (forest, beach, city, â€¦), Temperature (cold, warm, hot), budget (low, medium, high), purpose (business, leisure), number of people wish to travel with, families (0 or 1), Duration, Travel months, transportation (train, airplane, car, bus, ferry)

In [4]:
# Generate 10000 fake customer names using library
fake = Faker()
customer_names = [fake.name() for _ in range(10000)]

In [5]:
# Define other columns categories
genders = ['Male', 'Female']
ages = list(range(18, 65))
destination_cats = ["Mountain","City",
    "Countryside","Island","Ski Resort","Village",
    "Lake","Winery","Spa Retreat","Photography Expedition"]
temperatures = ['Cold', 'Warm', 'Hot']
budgets = ['Low', 'Medium', 'High']
purposes = ['Business', 'Leisure']
num_people = list(range(1, 6))
families = [0, 1] # indicator; 1=Y, 0=N
durations = list(range(1, 15))
travel_months = ['September','October', 'November']
transportation = ['Train', 'Airplane', 'Car', 'Bus', 'Ferry']
language = ['EN', 'FR', 'ZH']
hobby = ['Creative Arts', 'Physical Sports', 'Outdoor Exploration', 'Culinary', 'Intellectual Pursuits']

# Identify number of customer records to generate
num_records = 10000

# Generate data and put into dictionary form
customer_data = []
for _ in range(num_records):
    record = {
        'Name': random.choice(customer_names),
        'Gender': random.choice(genders),
        'Age': random.choice(ages),
        'Destination_Category': random.choice(destination_cats),
        'Temperature': random.choice(temperatures),
        'Budget': random.choice(budgets),
        'Purpose': random.choice(purposes),
        'Num_of_People': random.choice(num_people),
        'Families': random.choice(families),
        'Duration': random.choice(durations),
        'Travel Months': random.choice(travel_months),
        'Transportation': random.choice(transportation),
        'Hobby': random.choice(hobby),
        "Language": random.choice(language)
    }
    customer_data.append(record)

In [6]:
# Create a DataFrame
customer_df = pd.DataFrame(customer_data)

# Display the generated DataFrame
customer_df

,Name,Gender,Age,Destination_Category,Temperature,Budget,Purpose,Num_of_People,Families,Duration,Travel Months,Transportation,Hobby,Language
0,Danielle Liu,Female,51,Mountain,Warm,Low,Business,3,0,8,October,Airplane,Creative Arts,EN
1,Timothy Hurst,Male,35,Countryside,Hot,Low,Leisure,2,0,11,October,Train,Intellectual Pursuits,EN
2,Becky Larson DVM,Female,45,Photography Expedition,Hot,Low,Leisure,4,1,6,November,Ferry,Physical Sports,ZH
3,Mackenzie Allen,Male,52,City,Hot,Medium,Leisure,5,1,5,September,Bus,Creative Arts,ZH
4,Kenneth Clark,Female,26,Countryside,Warm,Medium,Leisure,4,0,13,October,Train,Outdoor Exploration,ZH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Daniel Reed,Female,46,Mountain,Cold,Low,Leisure,1,0,4,November,Airplane,Intellectual Pursuits,FR
9996,Christy Johnson,Female,59,Village,Hot,Low,Leisure,3,0,13,September,Train,Physical Sports,FR
9997,Nathaniel Young,Female,20,Spa Retreat,Cold,Low,Leisure,5,1,14,November,Ferry,Physical Sports,ZH
9998,Renee Holmes,Female,48,Countryside,Cold,High,Leisure,4,1,3,September,Train,Outdoor Exploration,FR
9999,Bradley Gutierrez,Female,59,Village,Warm,High,Business,5,1,1,November,Bus,Outdoor Exploration,FR

In [ ]:
customer_df.to_csv('customer.csv')

### Destination data: name, destination category (forest, beach, city, â€¦), Temperature (cold, warm, hot), budget (low, medium, high), purpose (business, leisure)

In [7]:
d = {'Dest_Name':["Montreal", "Toronto", "Halifax", "Vancouver", "Ottawa", "Manitoba",
                  "London", "Saskatoon", "Victoria", "Calgary", "Edmonton", "Winnipeg",
                 "Sherbrooke", "Mississauga", "Richmond", "Whitehorse", "Hamilton",
                 "Regina", "Yellowknife", "Niagara", "Vaughan", "Banff"],
        'Temp':['Cold', 'Hot', 'Warm', 'Hot', 'Warm', 'Cold',
                'Cold', 'Cold', 'Hot', 'Cold', 'Warm', 'Warm',
                'Warm', 'Cold', 'Warm', 'Cold', 'Warm',
                'Warm', 'Cold', 'Cold', 'Cold', 'Cold'],
        'Budget':['High', 'High', 'High', 'Med', 'Med', 'Med',
                  'Med', 'Low', 'High', 'High', 'High', 'Low',
                  'Med', 'Med', 'High', 'High', 'Med',
                  'Low', 'High', 'Med', 'Med', 'High'],
        'Purpose': ["Business", "Business", "Leisure", "Business", "Leisure", "Leisure",
                    "Leisure", "Leisure", "Leisure", "Leisure", "Leisure", "Leisure",
                    "Leisure", "Leisure", "Leisure", "Leisure", "Leisure",
                    "Leisure", "Leisure", "Leisure", "Leisure", "Leisure"],
        'Language':["FR", "EN", "EN", "EN", "EN", "EN",
                  "EN", "EN", "EN", "EN", "EN", "EN",
                 "FR", "EN", "EN", "EN", "EN",
                 "EN", "EN", "EN", "EN", "EN"],
        'Family_Friendly': ["Y", "Y", "Y", "Y", "Y", "Y",
                  "Y", "Y", "Y", "Y", "Y", "Y",
                 "Y", "Y", "Y", "Y", "Y",
                 "Y", "Y", "Y", "Y", "N"]}

destination_data = pd.DataFrame(data = d)
destination_data

      Dest_Name  Temp Budget   Purpose Language Family_Friendly
0      Montreal  Cold   High  Business       FR               Y
1       Toronto   Hot   High  Business       EN               Y
2       Halifax  Warm   High   Leisure       EN               Y
3     Vancouver   Hot    Med  Business       EN               Y
4        Ottawa  Warm    Med   Leisure       EN               Y
5      Manitoba  Cold    Med   Leisure       EN               Y
6        London  Cold    Med   Leisure       EN               Y
7     Saskatoon  Cold    Low   Leisure       EN               Y
8      Victoria   Hot   High   Leisure       EN               Y
9       Calgary  Cold   High   Leisure       EN               Y
10     Edmonton  Warm   High   Leisure       EN               Y
11     Winnipeg  Warm    Low   Leisure       EN               Y
12   Sherbrooke  Warm    Med   Leisure       FR               Y
13  Mississauga  Cold    Med   Leisure       EN               Y
14     Richmond  Warm   High   Leisure       EN               Y
15   Whitehorse  Cold   High   Leisure       EN               Y
16     Hamilton  Warm    Med   Leisure       EN               Y
17       Regina  Warm    Low   Leisure       EN               Y
18  Yellowknife  Cold   High   Leisure       EN               Y
19      Niagara  Cold    Med   Leisure       EN               Y
20      Vaughan  Cold    Med   Leisure       EN               Y
21        Banff  Cold   High   Leisure       EN               N

In [ ]:
destination_data.to_csv("dest_data.csv")

### Estimated cost: https://open.canada.ca/data/en/dataset/009f9a49-c2d9-4d29-a6d4-1a228da335ce/resource/8282db2a-878f-475c-af10-ad56aa8fa72c

The following cities within Canada was chosen based on the scope of the project: Montreal, Toronto, Halifax, Vancouver, Ottawa, Manitoba, London, Saskatoon, Victoria, Calgary, Edmonton, Winnipeg, Sherbrooke, Mississauga, Richmond, Whitehorse, Hamilton, Regina, Yellowknife, Niagara, Vaughan, Banff

In [ ]:
# import original csv
from google.colab import drive
drive.mount('/content/drive')
est_cost = pd.read_csv('/content/drive/MyDrive/travelq.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
est_cost.head()

,ref_number,disclosure_group,title_en,title_fr,name,purpose_en,purpose_fr,start_date,end_date,destination_en,...,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en,additional_comments_fr,owner_org,owner_org_title
0,T-20120-P11-001,SLE,Chief Executive Officer,PrÃ©sident directeur-gÃ©nÃ©ral,Philip Rizcallah,To attend meeting with Saskatchewan Provincial...,Pour assister Ã une rÃ©union avec le gouverneme...,2020-02-03,2020-02-04,"Regina, Saskatchewan, Canada",...,646.17,117.26,157.78,197.25,0.0,1118.46,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes dâ€™acce...
1,T-2020-P11-0001,SLE,Chair,PrÃ©sident,"BÃ©rubÃ©, Paul-Claude",Board members meeting,RÃ©union du conseil,2020-02-09,2020-02-13,"Vancouver, British Columbia, Canada",...,1104.27,189.72,841.31,461.84,NaN,2597.14,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes dâ€™acce...
2,T-2020-P11-0002,SLE,Vice Chair,vice-prÃ©sidente,"Reid, Mary",Board members meeting,RÃ©union du conseil,2020-02-09,2020-02-14,"Vancouver, British Columbia, Canada",...,2511.31,132.48,785.65,591.00,108.3,4128.74,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes dâ€™acce...
3,T-2020-P11-0003,SLE,Board Of Directors,Membre du conseil de direction,"McLaughlin, Joseph",Board members meeting,RÃ©union du conseil,2020-02-09,2020-02-12,"Vancouver, British Columbia, Canada",...,NaN,58.32,630.99,264.60,123.0,1076.91,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes dâ€™acce...
4,T-2020-P11-0004,SLE,Board Of Directors,Membre du conseil de direction,"Haan, Maureen",Board members meeting,RÃ©union du conseil,2020-02-09,2020-02-12,"Vancouver, British Columbia, Canada",...,880.99,192.76,630.99,332.45,NaN,2037.19,NaN,NaN,casdo-ocena,Accessibility Standards Canada | Normes dâ€™acce...

In [ ]:
cleaned_est = est_cost.dropna()
cleaned_est.count()

ref_number                8323
disclosure_group          8323
title_en                  8323
title_fr                  8323
name                      8323
purpose_en                8323
purpose_fr                8323
start_date                8323
end_date                  8323
destination_en            8323
destination_fr            8323
airfare                   8323
other_transport           8323
lodging                   8323
meals                     8323
other_expenses            8323
total                     8323
additional_comments_en    8323
additional_comments_fr    8323
owner_org                 8323
owner_org_title           8323
dtype: int64

In [ ]:
cleaned_est.dtypes

ref_number                 object
disclosure_group           object
title_en                   object
title_fr                   object
name                       object
purpose_en                 object
purpose_fr                 object
start_date                 object
end_date                   object
destination_en             object
destination_fr             object
airfare                   float64
other_transport           float64
lodging                   float64
meals                     float64
other_expenses            float64
total                     float64
additional_comments_en     object
additional_comments_fr     object
owner_org                  object
owner_org_title            object
dtype: object

In [ ]:
# select designated city data only
est_cost_CAN = cleaned_est[cleaned_est['destination_en'].str.contains("Montreal|MontrÃ©al|Toronto|Halifax|Vancouver|Ottawa|Manitoba|London|Saskatoon|Victoria|Calgary|Edmonton|Winnipeg|Sherbrooke|Mississauga|Richmond|Whitehorse|Hamilton|Regina|Yellowknife|Niagara|Vaughan|Banff", case = False)]

In [ ]:
# drop unnecessary columns and reset index
trunc_cost_CAN = est_cost_CAN.drop(columns = ["disclosure_group", "title_fr", "purpose_fr", "destination_fr", "additional_comments_fr", "owner_org", "owner_org_title"])
trunc_cost_CAN.reset_index(drop = True)

,ref_number,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
0,T-2019-Q1-007,"Chairperson, Canada Agricultural Review Tribun...","BÃ©langer, Luc",Attend various meetings on various dates,2019-04-01,2019-05-30,"Ottawa, ON",0.00,0.00,0.00,0.00,950.25,950.25,Parking fees reimbursed for various dates
1,T-2019-P3-0001,Chairperson,"Aterman, Paul",CCAT Symposium,2019-05-25,2019-05-28,Montreal (Quebec) Canada,0.00,241.96,464.10,153.20,-105.00,754.26,Negative amount in Other expenses is due to Mr...
2,T-2019-P3-0008,Chairperson,"Brazeau, Ginette",Toronto - Cancelled trip \r\nThe hearing was r...,2019-06-21,2019-06-21,Toronto (Ontario) Canada,560.07,0.00,0.00,0.00,113.00,673.07,Porter Credit available is $560.07 \r\nCancell...
3,T-2019-P3-0010,Deputy Chief Administrator,"Covelli, Nick",CCAT Symposium,2019-05-26,2019-05-28,Montreal (Quebec) Canada,0.00,231.33,817.53,223.95,0.00,1272.81,Mr. Covelli was replacing Mrs. Catherine Ebbs
4,T-2019-P4-0001,Chairperson,"BÃ©langer, Luc",Meeting for work,2019-06-17,2019-06-21,"Halifax, N.S. & Quebec, Quebec, Canada",1190.90,671.69,917.06,451.50,0.00,3231.15,The flight from Montreal to Quebec City had te...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5583,WD-DEO_TRAV_q4_2018_8641,"Assistant Deputy Minister, Policy and Strategi...",Barbara Motzney,Meeting with Regional Development Agency gover...,2019-01-14,2019-01-15,"Montreal,QC",0.00,410.20,224.91,177.25,12.43,824.79,Correction to Other Transport($157.45)
5584,TRAV_WD_8762,Assistant Deputy Minister (British Columbia),Gerry Salembier,Attend various meetings with Federal Governmen...,2019-12-16,2019-12-18,"Edmonton, AB",92.40,180.57,357.02,194.20,12.32,836.51,Airfare booked on flight pass.
5585,TRAV_WD_8763,Assistant Deputy Minister (British Columbia),Gerry Salembier,"Air Canada East-West Connector Flight Pass, ex...",2020-01-28,2020-01-28,"Edmonton, Alberta; Calgary, Alberta; Ottawa, O...",388.19,0.00,0.00,0.00,0.00,388.19,To extend flight pass
5586,TRAV_WD_8776,Assistant Deputy Minister (British Columbia),Gerry Salembier,Attend Executive Committee meeting,2020-01-28,2020-01-29,"Edmonton, Alberta",92.40,185.00,178.51,126.35,12.43,594.69,Airfare booked using flight pass
5587,TRAV_WD_8805,Assistant Deputy Minister (British Columbia),Gerry Salembier,Represent WD at the House Standing Committee o...,2020-03-08,2020-03-12,"Ottawa, Ontario",60.90,105.09,822.64,452.50,12.43,1453.56,Airfare booked using flight pass

In [ ]:
# check name
trunc_cost_CAN.value_counts('name')

name
Catherine McKenna    67
Jean-Yves Duclos     62
Chris Alexander      59
Stephen Lucas        53
Tim Uppal            48
                     ..
Millar, Samuel        1
Miller, Marc          1
Miller, Patricia      1
Minden, Daniel        1
 Montminy, JoÃ«lle     1
Length: 1356, dtype: int64

In [ ]:
trunc_cost_CAN.loc[trunc_cost_CAN['name'] == 'Catherine McKenna']

,ref_number,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
44459,T-2016-Q4-00005,Minister,Catherine McKenna,To attend the Prime Minister's Cabinet retreat,2017-01-22,2017-01-25,"Calgary, Alberta",2280.17,0.0,569.19,233.20,0.0,3082.56,AMC430007
44496,T-2017-Q1-00027,Minister,Catherine McKenna,To meet with key stakeholders in Mauricie and ...,2017-02-26,2017-02-28,"Mauricie & Montreal, Quebec",0.00,0.0,386.76,79.80,0.0,466.56,AMC413074
44497,T-2017-Q1-00028,Minister,Catherine McKenna,To meet key stakeholders in Banff,2017-03-09,2017-03-10,"Banff, Alberta",1757.31,0.0,234.14,45.55,0.0,2037.00,AMC478002
44500,T-2017-Q1-00031,Minister,Catherine McKenna,To attend the Globe Conference in Toronto and ...,2017-04-03,2017-04-05,"Toronto, Ontario; Montreal, Quebec",513.54,0.0,497.59,80.25,0.0,1091.38,AMC460604
44502,T-2017-Q1-00033,Minister,Catherine McKenna,To make an announcement in Halifax,2017-04-26,2017-04-26,"Halifax, Nova Scotia",1149.08,0.0,0.00,63.10,0.0,1212.18,AMC419617
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45347,T-2019-P6-0019,Minister,Catherine McKenna,To meet with Stakeholders,2019-08-06,2019-08-09,"Toronto, Ontario, Canada; Hamilton, Ontario, C...",1042.14,0.0,337.28,141.90,0.0,1521.32,AMC451027
45348,T-2019-P6-0020,Minister,Catherine McKenna,To meet with Stakeholders,2019-08-13,2019-08-15,"Charlottetown, Prince Edward Island, Canada; M...",1195.09,0.0,524.87,233.15,0.0,1953.11,AMC436440
45349,T-2019-P6-0021,Minister,Catherine McKenna,To meet with Stakeholders,2019-08-26,2019-08-27,"Toronto, Ontario, Canada",1136.96,0.0,305.66,71.15,0.0,1513.77,AMC451434
45350,T-2019-P6-0022,Minister,Catherine McKenna,To meet with stakeholders and join the Governm...,2019-08-18,2019-08-23,"Yellowknife, Northwest Territories, Canada; Wh...",4774.35,326.0,1236.81,479.40,0.0,6816.56,AMC46815
45364,T-2019-P6-0036,Minister,Catherine McKenna,Announcement,2019-09-03,2019-09-04,"Toronto, Ontario, Canada",1002.20,12.6,305.66,125.85,0.0,1446.31,AMC466710

In [ ]:
trunc_cost_CAN.value_counts('ref_number')

ref_number
T-2019-P7-0001              9
T-2019-P7-0002              7
T-2023-P11-0002             6
T-2019-P6-0001              6
T-2023-P12-0004             6
                           ..
T-2019-P3-0018              1
T-2019-P3-0019              1
T-2019-P3-0020              1
T-2019-P3-0021              1
WD-DEO_TRAV_q4_2018_8641    1
Length: 4730, dtype: int64

In [ ]:
trunc_cost_CAN.loc[trunc_cost_CAN['ref_number'] == 'T-2019-P7-0001']

,ref_number,title_en,name,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
8970,T-2019-P7-0001,"Deputy Minister, President","Brassard, Manon",Various meetings,2019-10-02,2019-10-03,"Quebec, Quebec and Ottawa, Ontario, Canada",464.61,0.00,243.95,176.65,0.00,885.21,Additional fees invoiced and paid in P8
9097,T-2019-P7-0001,"Executive Vice-President, Transparency and Str...","Sletto, Tracy",Attend the IAMC-TMX Committee Meeting #20,2019-09-10,2019-09-12,"Vancouver, British Columbia, Canada",627.80,168.50,445.44,203.85,31.50,1477.09,Other - baggage
15117,T-2019-P7-0001,President and Chief Executive Officer,"Tennier, Anne",Participated in the Health and Safety Leadersh...,2019-10-22,2019-10-23,"Toronto, Ontario, Canada",0.00,97.89,217.41,34.60,60.00,409.90,Parking
15585,T-2019-P7-0001,Chief Commissioner,"Miller, Patricia",Canadian Food Inspection Agency (CFIA) Meetings,2019-09-09,2019-09-09,"Ottawa (Ontario), Canada",0.00,0.00,247.47,0.00,0.00,247.47,Hotel cancellation fees- meeting cancelled las...
45369,T-2019-P7-0001,Parliamentary Secretary,"Fraser, Sean",To meet with stakeholders,2019-04-24,2019-04-26,"Vancouver, Prince George, British Columbia, Ca...",4280.78,41.00,274.39,305.55,0.00,4901.72,AMC460161
58569,T-2019-P7-0001,Federal Co-Chair,Andrew Noseworthy,Attend the Assistant Deputy Minister Clean Gro...,2018-09-19,2018-09-20,"Ottawa, Ontario, Canada",541.62,0.00,0.00,0.00,0.00,541.62,Trip cancelled. ADM unable to travel.
64504,T-2019-P7-0001,Commissioner,Claude Joli CÅ“ur,Meeting with: The Canadian Media Producers Ass...,2019-09-03,2019-09-06,"Toronto, Ontario, Canada",413.89,240.61,652.23,285.05,0.00,1591.78,ANQ990750
69600,T-2019-P7-0001,Interim President,"Jayas, Digvir",Executive committee meeting and Canada Researc...,2019-09-19,2019-09-20,"Ottawa, Ontario, Canada",571.20,69.21,252.67,217.10,75.10,1185.28,Previous Period
79539,T-2019-P7-0001,Associate Vice President Future Challenges,"Gobel, Ursula",To seek feedback and comments from Indigenous ...,2019-07-28,2019-08-03,"Yellowknife & Inuvik, Northwest Territories, C...",3330.86,56.60,1059.90,829.10,70.06,5346.52,Previous Period

In [ ]:
# drop ref_number, title_en, and name as title_en is not necessary, and ref_number and name have same value for different records
trunc_cost_CAN = trunc_cost_CAN.drop(columns = ["ref_number", "title_en", "name"])
trunc_cost_CAN.head()

,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
395,Attend various meetings on various dates,2019-04-01,2019-05-30,"Ottawa, ON",0.00,0.00,0.00,0.00,950.25,950.25,Parking fees reimbursed for various dates
397,CCAT Symposium,2019-05-25,2019-05-28,Montreal (Quebec) Canada,0.00,241.96,464.10,153.20,-105.00,754.26,Negative amount in Other expenses is due to Mr...
404,Toronto - Cancelled trip \r\nThe hearing was r...,2019-06-21,2019-06-21,Toronto (Ontario) Canada,560.07,0.00,0.00,0.00,113.00,673.07,Porter Credit available is $560.07 \r\nCancell...
406,CCAT Symposium,2019-05-26,2019-05-28,Montreal (Quebec) Canada,0.00,231.33,817.53,223.95,0.00,1272.81,Mr. Covelli was replacing Mrs. Catherine Ebbs
409,Meeting for work,2019-06-17,2019-06-21,"Halifax, N.S. & Quebec, Quebec, Canada",1190.90,671.69,917.06,451.50,0.00,3231.15,The flight from Montreal to Quebec City had te...

In [ ]:
# check destination
trunc_cost_CAN.value_counts(["destination_en"])

destination_en
Toronto, Ontario, Canada                                                                                                   889
Ottawa, Ontario, Canada                                                                                                    550
Vancouver, British Columbia, Canada                                                                                        273
Montreal, Quebec, Canada                                                                                                   251
Toronto, Ontario                                                                                                           206
                                                                                                                          ...
MontrÃ©al, Quebec, Canada; LÃ©vis, Quebec, Canada; Saguenay, Quebec, Canada; Alma, Quebec, Canada; QuÃ©bec, Quebec, Canada      1
MontrÃ©al, Quebec, Canada; QuÃ©bec, Quebec, Canada; Sherbrooke, Quebec, Canada                                                 1
MontrÃ©al, Quebec, Canada; QuÃ©bec, Quebec, Canada; Toronto, Ontario, Canada                                                   1
MontrÃ©al, Quebec, Canada; Thetford Mines, Quebec, Canada; Sherbrooke, Quebec, Canada                                         1
York, Ontario, Canada; Hamilton, Ontario, Canada                                                                             1
Length: 1042, dtype: int64

In [ ]:
# check city names
trunc_cost_CAN["destination_en"].unique

<bound method Series.unique of 395                                             Ottawa, ON
397                               Montreal (Quebec) Canada
404                               Toronto (Ontario) Canada
406                               Montreal (Quebec) Canada
409                 Halifax, N.S. & Quebec, Quebec, Canada
                               ...
88035                                          Montreal,QC
88054                                         Edmonton, AB
88066    Edmonton, Alberta; Calgary, Alberta; Ottawa, O...
88069                                    Edmonton, Alberta
88089                                      Ottawa, Ontario
Name: destination_en, Length: 5588, dtype: object>

In [ ]:
# unified city name for Montreal/MontrÃ©al
trunc_cost_CAN['destination_en'] = trunc_cost_CAN['destination_en'].apply(lambda x: ' '.join(word.capitalize() for word in x.split()))
trunc_cost_CAN['destination_en'] = trunc_cost_CAN['destination_en'].str.replace("Montreal","MontrÃ©al")

In [ ]:
# filtered out records with multiple locations in destination_en column
multi_location = trunc_cost_CAN[trunc_cost_CAN['destination_en'].str.contains(";|&", case = False)]
multi_location

,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
409,Meeting for work,2019-06-17,2019-06-21,"Halifax, N.s. & Quebec, Quebec, Canada",1190.90,671.69,917.06,451.50,0.00,3231.15,The flight from Montreal to Quebec City had te...
1170,To attend the Western Outreach,2019-07-03,2019-07-16,Vancouver (british Columbia) Canada; Victoria ...,3913.46,320.70,2375.51,1067.45,0.00,7677.12,Airfare credit anticipated which will be appli...
1174,To accompany the Minister for an announcement ...,2019-07-17,2019-07-19,Saskatoon (saskatchewan) Canada; Quebec (quebe...,1908.43,508.70,1134.17,349.80,375.00,4276.10,Other expenses: Conference fee
1196,To attend the Alberta Outreach,2019-08-12,2019-08-15,Calgary (alberta) Canada; Lethbridge (alberta)...,1123.61,37.35,379.46,253.25,157.50,1951.17,Other expenses: Conference fee
1213,Make announcements in Rouyn-Noranda; attend Ca...,2019-08-25,2019-08-27,Rouyn-noranda (quebec) Canada; MontrÃ©al (quebe...,1334.74,0.00,381.40,166.45,0.00,1882.59,Air Canada flight was cancelled. A refund will...
...,...,...,...,...,...,...,...,...,...,...,...
87920,Attend Deputy Ministers Retreats; Attend meeti...,2019-01-14,2019-01-24,"MontrÃ©al, Qc; Toronto, On; Ottawa, On",3788.71,289.91,2611.47,1031.35,24.86,7746.11,Correction to Other ($12.43)
87937,Attend meetings with Privy Council Office; att...,2018-04-22,2018-04-26,"Calgary, Ab; Vancouver, Bc",1410.41,270.91,1008.46,395.30,12.43,3097.51,Change to Air Fare (HRG Fee)
87938,Deliver speech for Global Federation of Compet...,2018-09-13,2018-10-01,"Winnipeg, Mb; Buenos Aires, Argentina",6475.35,247.98,1994.47,724.06,12.43,9454.29,Change to Purpose of Travel
87975,Attend G&C Program Management Steering Committ...,2018-05-07,2018-05-10,"Ottawa, On; Winnipeg, Mb",1111.92,147.47,701.58,310.40,12.43,2306.38,Correction to Other Transportation ($26.02)
88066,"Air Canada East-West Connector Flight Pass, ex...",2020-01-28,2020-01-28,"Edmonton, Alberta; Calgary, Alberta; Ottawa, O...",388.19,0.00,0.00,0.00,0.00,388.19,To extend flight pass

In [ ]:
multi_location[multi_location['destination_en'].str.contains("Montreal", case = False)]

Empty DataFrame
Columns: [purpose_en, start_date, end_date, destination_en, airfare, other_transport, lodging, meals, other_expenses, total, additional_comments_en]
Index: []

In [ ]:
multi_location['destination_en']

409                 Halifax, N.s. & Quebec, Quebec, Canada
1170     Vancouver (british Columbia) Canada; Victoria ...
1174     Saskatoon (saskatchewan) Canada; Quebec (quebe...
1196     Calgary (alberta) Canada; Lethbridge (alberta)...
1213     Rouyn-noranda (quebec) Canada; MontrÃ©al (quebe...
                               ...
87920                MontrÃ©al, Qc; Toronto, On; Ottawa, On
87937                           Calgary, Ab; Vancouver, Bc
87938                Winnipeg, Mb; Buenos Aires, Argentina
87975                             Ottawa, On; Winnipeg, Mb
88066    Edmonton, Alberta; Calgary, Alberta; Ottawa, O...
Name: destination_en, Length: 721, dtype: object

In [ ]:
trunc_cost_CAN['destination_en']

395                              Ottawa, On
397                MontrÃ©al (quebec) Canada
404                Toronto (ontario) Canada
406                MontrÃ©al (quebec) Canada
412      Vancouver, Britsh Columbia, Canada
                        ...
87977                           Calgary, Ab
88035                           MontrÃ©al,qc
88054                          Edmonton, Ab
88069                     Edmonton, Alberta
88089                       Ottawa, Ontario
Name: destination_en, Length: 4399, dtype: object

In [ ]:
# use index to separate the original dataset into two based on value in destination_en column
multi_location_index = multi_location.index.to_list()
trunc_cost_CAN = trunc_cost_CAN.drop(multi_location_index)

KeyError: ignored

In [ ]:
# checked to see whether records with multivalue destinations are removed
trunc_cost_CAN.loc(87920)

ValueError: ignored

In [ ]:
# remove unneeded dates
trunc_cost_CAN = trunc_cost_CAN.loc[trunc_cost_CAN["start_date"] < '2023-01-31',:]

In [ ]:
trunc_cost_CAN.value_counts(["start_date"])

start_date
2023-01-22    21
2023-01-23    18
2020-01-18    15
2022-09-05    15
2022-09-06    15
              ..
2017-06-06     1
2017-06-04     1
2017-06-03     1
2017-06-02     1
2018-09-07     1
Length: 1756, dtype: int64

In [ ]:
# reset index
trunc_cost_CAN.reset_index(drop = True)

,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
0,Attend various meetings on various dates,2019-04-01,2019-05-30,"Ottawa, On",0.00,0.00,0.00,0.00,950.25,950.25,Parking fees reimbursed for various dates
1,CCAT Symposium,2019-05-25,2019-05-28,MontrÃ©al (quebec) Canada,0.00,241.96,464.10,153.20,-105.00,754.26,Negative amount in Other expenses is due to Mr...
2,Toronto - Cancelled trip \r\nThe hearing was r...,2019-06-21,2019-06-21,Toronto (ontario) Canada,560.07,0.00,0.00,0.00,113.00,673.07,Porter Credit available is $560.07 \r\nCancell...
3,CCAT Symposium,2019-05-26,2019-05-28,MontrÃ©al (quebec) Canada,0.00,231.33,817.53,223.95,0.00,1272.81,Mr. Covelli was replacing Mrs. Catherine Ebbs
4,Vancouver - Cancelled trip\r\nHearing being ca...,2019-07-29,2019-08-02,"Vancouver, Britsh Columbia, Canada",2989.79,0.00,0.00,0.00,0.00,2989.79,"Air Canada Credit available is $2,964.93\r\nHR..."
...,...,...,...,...,...,...,...,...,...,...,...
4394,Various meetings with stakeholders,2017-10-15,2017-10-16,"Calgary, Ab",725.33,122.98,50.00,148.40,12.43,1059.14,AMENDMENT: Correction to Airfare (2018-06-25)
4395,Meeting with Regional Development Agency gover...,2019-01-14,2019-01-15,"MontrÃ©al,qc",0.00,410.20,224.91,177.25,12.43,824.79,Correction to Other Transport($157.45)
4396,Attend various meetings with Federal Governmen...,2019-12-16,2019-12-18,"Edmonton, Ab",92.40,180.57,357.02,194.20,12.32,836.51,Airfare booked on flight pass.
4397,Attend Executive Committee meeting,2020-01-28,2020-01-29,"Edmonton, Alberta",92.40,185.00,178.51,126.35,12.43,594.69,Airfare booked using flight pass
4398,Represent WD at the House Standing Committee o...,2020-03-08,2020-03-12,"Ottawa, Ontario",60.90,105.09,822.64,452.50,12.43,1453.56,Airfare booked using flight pass

In [ ]:
trunc_cost_CAN.to_csv("single_city_cost_CAN.csv")

In [ ]:
multi_location.reset_index(drop = True)

,purpose_en,start_date,end_date,destination_en,airfare,other_transport,lodging,meals,other_expenses,total,additional_comments_en
0,Meeting for work,2019-06-17,2019-06-21,"Halifax, N.s. & Quebec, Quebec, Canada",1190.90,671.69,917.06,451.50,0.00,3231.15,The flight from Montreal to Quebec City had te...
1,To attend the Western Outreach,2019-07-03,2019-07-16,Vancouver (british Columbia) Canada; Victoria ...,3913.46,320.70,2375.51,1067.45,0.00,7677.12,Airfare credit anticipated which will be appli...
2,To accompany the Minister for an announcement ...,2019-07-17,2019-07-19,Saskatoon (saskatchewan) Canada; Quebec (quebe...,1908.43,508.70,1134.17,349.80,375.00,4276.10,Other expenses: Conference fee
3,To attend the Alberta Outreach,2019-08-12,2019-08-15,Calgary (alberta) Canada; Lethbridge (alberta)...,1123.61,37.35,379.46,253.25,157.50,1951.17,Other expenses: Conference fee
4,Make announcements in Rouyn-Noranda; attend Ca...,2019-08-25,2019-08-27,Rouyn-noranda (quebec) Canada; MontrÃ©al (quebe...,1334.74,0.00,381.40,166.45,0.00,1882.59,Air Canada flight was cancelled. A refund will...
...,...,...,...,...,...,...,...,...,...,...,...
716,Attend Deputy Ministers Retreats; Attend meeti...,2019-01-14,2019-01-24,"MontrÃ©al, Qc; Toronto, On; Ottawa, On",3788.71,289.91,2611.47,1031.35,24.86,7746.11,Correction to Other ($12.43)
717,Attend meetings with Privy Council Office; att...,2018-04-22,2018-04-26,"Calgary, Ab; Vancouver, Bc",1410.41,270.91,1008.46,395.30,12.43,3097.51,Change to Air Fare (HRG Fee)
718,Deliver speech for Global Federation of Compet...,2018-09-13,2018-10-01,"Winnipeg, Mb; Buenos Aires, Argentina",6475.35,247.98,1994.47,724.06,12.43,9454.29,Change to Purpose of Travel
719,Attend G&C Program Management Steering Committ...,2018-05-07,2018-05-10,"Ottawa, On; Winnipeg, Mb",1111.92,147.47,701.58,310.40,12.43,2306.38,Correction to Other Transportation ($26.02)
720,"Air Canada East-West Connector Flight Pass, ex...",2020-01-28,2020-01-28,"Edmonton, Alberta; Calgary, Alberta; Ottawa, O...",388.19,0.00,0.00,0.00,0.00,388.19,To extend flight pass

In [ ]:
multi_location.to_csv("multi_city_cost_CAN.csv")

### YUL to other cities airfare, round-way, one way per record, for 30days

In [ ]:
d2 = {'Flight':["YUL-YYZ",
               "YHZ-YYZ",
               "YVR-YYZ",
               "YOW-YYZ",
               "YWG-YYZ",
               "YXE-YYZ",
               "YYJ-YYZ",
               "YYC-YYZ",
               "YEG-YYZ",
               "YXY-YYZ",
               "YQR-YYZ",
               "YZF-YYZ"]
               #"Richmond","Hamilton","Sherbrooke","Niagara","Vaughan","Banff", "London"],
}

In [ ]:
num_keys = 30  # Number of keys to generate
base_key = 'price'  # Base text for keys

price = {}
for i in range(1, num_keys+1):
    price[f'{base_key}_day{i}'] = [
         random.randint(198, 516), #"YUL-YYZ",
         random.randint(242, 690), #"YHZ-YYZ",
         random.randint(530, 960), #"YVR-YYZ",
         random.randint(121, 517), #"YOW-YYZ",
         random.randint(315, 1600), #"YWG-YYZ",
         random.randint(550, 1500), #"YXE-YYZ",
         random.randint(422, 890), #"YYJ-YYZ",
         random.randint(257, 640), #"YYC-YYZ",
         random.randint(385, 732), #"YEG-YYZ",
         random.randint(900, 1400), #"YXY-YYZ",
         random.randint(170, 400), #"YQR-YYZ",
         random.randint(480, 660)] #"YZF-YYZ"

In [ ]:
d2.update(price)

In [ ]:
airfare_data = pd.DataFrame(data = d2)
airfare_data

,Flight,price_day1,price_day2,price_day3,price_day4,price_day5,price_day6,price_day7,price_day8,price_day9,...,price_day21,price_day22,price_day23,price_day24,price_day25,price_day26,price_day27,price_day28,price_day29,price_day30
0,YUL-YYZ,507,290,434,315,259,227,280,420,319,...,299,350,425,462,312,267,431,223,386,475
1,YHZ-YYZ,328,568,261,586,311,541,593,673,586,...,473,414,404,515,247,277,469,330,250,446
2,YVR-YYZ,904,762,789,858,785,870,715,766,656,...,680,573,672,740,859,955,575,715,680,604
3,YOW-YYZ,448,213,202,254,179,190,220,170,457,...,270,232,403,481,434,414,159,277,378,479
4,YWG-YYZ,1030,1136,753,1233,1239,924,1034,1226,1277,...,1378,1069,1488,649,574,1348,1262,1302,1192,763
5,YXE-YYZ,812,775,1242,804,1174,1306,1320,794,883,...,1252,1448,1331,748,1332,613,1133,1105,1296,1027
6,YYJ-YYZ,671,549,720,561,586,745,834,571,520,...,815,472,565,665,447,621,484,561,427,715
7,YYC-YYZ,393,285,563,349,379,370,581,273,358,...,499,353,271,632,288,317,438,384,557,611
8,YEG-YYZ,402,521,392,597,704,461,695,689,469,...,558,523,620,703,609,493,710,609,567,620
9,YXY-YYZ,1245,1378,976,1091,1221,1189,916,1086,1380,...,1309,1269,1381,1052,1055,947,1110,1098,1315,1081
10,YQR-YYZ,294,397,183,173,382,197,334,399,306,...,334,380,221,360,395,319,303,183,312,210
11,YZF-YYZ,552,594,522,510,629,498,492,506,589,...,562,519,517,519,558,583,505,482,569,574

In [ ]:
airfare_data.to_csv("airfare_data.csv")